### ISSUE TITLE
[Tech Improvement #1] Uses DFS to build DOM tree bottom up

### ISSUE THREAD

**Issue by TheMarvelousWhale** [TheMarvelousWhale/stonk_scripts#4]
If we were to use a build yml to dynamically construct our tree from a file

```
main: 
  type: widget
  layout_obj: qhbox
  child_widgets: 
    side_col:
        type: widget
        layout_obj: qvbox
        child_widgets: 
          anya_gif: 
            type: gif
            filepath: "../media/anya.gif"
    graph_col: 
        type: widget
```
The we need a better dom parser that can read the yaml, do dfs to build the tree from bottom

We also need to add event registration in widget controller
